server:
  port: 8084

spring:
  application:
    name: appointment-booking-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

resilience4j:
  retry:
      instances:
        doctorRetry:
          maxAttempts: 3
          waitDuration: 2s
          eventConsumerBufferSize: 10
  circuitbreaker:
    instances:
      doctorService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

  ratelimiter:
    instances:
      doctorRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 30s
        timeoutDuration: 0

  timelimiter:
    instances:
      doctorTimeLimiter:
        timeoutDuration: 3s
        cancelRunningFuture: true

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG

management:
  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health